### ISSUE TITLE
Execute an operator in a given CPU core

### ISSUE THREAD

**Issue by felipegutierrez** [felipegutierrez/explore-flink#12]
Operator's threads are bouncing between different cores, which is normal because th Operating Systems is optimizing the execution of threads to the JVM. However, we need to have an operator fixed in a given CPU core in order to have a more precise mathematical model, even though it will decrease the performance of the whole application. This can be done by using the Thread Affinity library from issue #10 .

**Comment by abelpc** [comment]
We need an option for pinning (fixing) one or more operators' threads to CPU cores. If there are more operator threads than cores, load-balancing threads among available cores should take place; for instance, if the stream application detects 2 cores and we have 4 operator threads, the thread placement would be: 

- **Thread 1**: Core 0 
- **Thread 2**: Core 1
- **Thread 3**: Core 0
- **Thread 4**: Core 1
-------------------------------
- **Thread n**: Core (**n** _mod_ **Total_Number_of_cores**)

Otherwise, if there are more cores than operators, try pinning operators to cores not sharing the same L1 cache (if possible). This option should also support "no-pinning", leaving the thread placement policy to the OS scheduler (default and current behavior).

This option will create predictability in application's total runtime, enabling easier experimental analysis. However, it will not necessarily increase or decrease application's performance.

**Comment by felipegutierrez** [comment]
Pinning operator' thread to specific CPU cores is implemented. To enable this policy we have to use the parameter `-pinningPolicy true` when launching the stream application. Below is the screenshot of the Grafana panel showing that the operator's threads are not bouncing among different CPU cores.

![Screenshot from 2019-11-01 17-01-42](https://user-images.githubusercontent.com/5030696/68038060-5d923600-fcc9-11e9-981b-1ffa024b99d3.png)
